apiVersion: v1
kind: ConfigMap
metadata:
  name: inferno-configmap
data:
  auth: |
    #!/dis/sh.dis -n
    load std
    or {ftest -e /net/dns} {ftest -e /env/emuhost} {ndb/dns}
    or {ftest -e /net/cs} {ndb/cs}
    or {ftest -f /keydb/signerkey} {echo 'auth: need to use createsignerkey(8)' >[1=2]; raise nosignerkey}
    or {ftest -f /keydb/keys} {echo 'auth: need to create /keydb/keys' >[1=2]; raise nokeys}
    and {auth/keyfs -n /keydb/password} {
      listen -v -t -A 'tcp!*!inflogin' {auth/logind&}
      listen -v -t -A 'tcp!*!infkey' {auth/keysrv&}
      listen -v -t -A 'tcp!*!infsigner' {auth/signer&}
      listen -v -t -A 'tcp!*!infcsigner' {auth/countersigner&}
    }
  registry: |
    #!/dis/sh.dis -n
    load std
    or {ftest -f /mnt/registry/new} {
      db=()
      and {ftest -f /lib/ndb/registry} {db=(-f /lib/ndb/registry)}
      mount -A -c {ndb/registry $db} /mnt/registry
    }
    listen -A -v -s 'tcp!*!registry' {export /mnt/registry&}	# -n?
  styx: |
    #!/dis/sh.dis -n
    load std
    or {ftest -e /net/dns} {ftest -e /env/emuhost} {ndb/dns}
    or {ftest -e /net/cs} {ndb/cs}
    listen -A -v -s 'tcp!*!styx' {export /&}
