apiVersion: apps/v1
kind: Deployment
metadata:
  name: inferno-styx-deployment
  labels:
    app: inferno-styx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inferno-styx
  template:
    metadata:
      labels:
        app: inferno-styx
    spec:
      containers:
      - name: inferno-os
        image: caerwyn/inferno-os:latest
        command: ["emu"]
        args: ["sh", "-i", "-v", "/dis/scripts/styx"]
        ports:
        - containerPort: 6666
          name: styx
        volumeMounts:
        - name: keyring
          mountPath: "/usr/inferno/usr/inferno/keyring"
          readOnly: true
        - name: scripts
          mountPath: "/usr/inferno/dis/scripts"
      volumes:
      - name: keyring
        secret: 
          secretName: inferno-keyring
          optional: false
      - name: scripts
        configMap:
          name: inferno-configmap
          defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: inferno-styx-service
spec:
  selector:
    app: inferno-styx
  ports:
    - protocol: TCP
      port: 6666
      targetPort: 6666
