#!/dis/sh.dis -n
load std
or {ftest -e /net/dns} {ftest -e /env/emuhost} {ndb/dns}
or {ftest -e /net/cs} {ndb/cs}
or {ftest -f /mnt/registry/new} {
	db=()
	and {ftest -f /lib/ndb/registry} {db=(-f /lib/ndb/registry)}
	mount -A -c {ndb/registry $db} /mnt/registry
}
listen -A -v -s 'tcp!*!registry' {export /mnt/registry&}	# -n?
